"""Pytest plumbing: collects Test ID / Scenario / Input / Expected / Actual / Result
into docs/test_report.md after every run (numbers come from the real run)."""
import os
import pytest

_ROWS = []


@pytest.fixture
def actual(request):
    """Call actual('text') inside a test to record the observed result."""
    def _set(text):
        request.node.user_properties.append(("actual", str(text)))
    return _set


@pytest.hookimpl(hookwrapper=True)
def pytest_runtest_makereport(item, call):
    outcome = yield
    rep = outcome.get_result()
    if rep.when != "call":
        return
    doc = [l.strip() for l in (item.function.__doc__ or "").strip().splitlines()]
    scenario = doc[0] if doc else item.name
    get = lambda p: next((l[len(p):].strip() for l in doc if l.startswith(p)), "")
    act = dict(rep.user_properties).get("actual", "")
    _ROWS.append((item.name.split("_")[1].upper(), scenario, get("Input:"), get("Expected:"), act,
                  "PASS" if rep.passed else "FAIL"))


def pytest_sessionfinish(session, exitstatus):
    if not _ROWS:
        return
    path = os.path.join(os.path.dirname(os.path.dirname(__file__)), "docs", "test_report.md")
    esc = lambda s: str(s).replace("|", "\\|").replace("\n", " ")
    lines = ["# Automated Test Report", "",
             "Generated by pytest on every run. 'Actual' is recorded by each test.", "",
             "| Test ID | Scenario | Input | Expected | Actual | Result |", "|---|---|---|---|---|---|"]
    lines += ["| " + " | ".join(esc(c) for c in row) + " |" for row in sorted(_ROWS)]
    passed = sum(1 for r in _ROWS if r[-1] == "PASS")
    lines += ["", f"**{passed}/{len(_ROWS)} passed**"]
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
